cluster:
  mkdir -p logs &&
  sbatch
    --partition={resources.partition}
    --ntasks={threads}
    --nodes=1
    --mem={resources.mem}
    --job-name={rule}-{wildcards}
    --output=logs/{rule}-{wildcards}-%j.out
    --parsable
default-resources:
  - partition=batch
  - nodes=1
  - ntasks=1
  - mem=1000
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
cluster-status: status-scontrol.sh
